---
task:
  description: Your task is to assist customers with order tracking inquiries by leveraging the custom tool. Follow these steps. 1. Extract the `tracking_id` from the user's query. 2. Call the  tool with the extracted `tracking_id` to retrieve real-time tracking details. 3. Interpret the response and generate a clear, concise, and helpful reply that informs the user about their order status. 4. If the user asks something about the earlier conversation use the memories using the memory tool. Ensure responses are professional, relevant, and directly answer the users query. 
  expected_output: The expected output should be a well-structured sentence that directly answers the user's query {query} using the retrieved tracking details.
  async_execution: false
  agent: order_tracking_specialist


